spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  secret-key: ${SECRET-KEY}

#security:
#  jwt:
#    header:
#    secret:
#    token-validity-in-seconds:
#
#aws:
#  accessKeyId:AKIA2WSJ73WOI2ZIWIMW
#  secretKey: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
#  region:ap-northeast-2
#  s3:
#    bucketName:project2team

logging:
  level:
    org.springframework.security: DEBUG





