spring:
  datasource:
    username: backend2team
    password: supercoding09
    url: jdbc:mariadb://db-project3.cryqvukdhzno.ap-northeast-2.rds.amazonaws.com:3306/communityRoom
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  secret-key: supercoding
#security:
#  jwt:
#    header:
#    secret:
#    token-validity-in-seconds:
#
#aws:
#  accessKeyId:
#  secretKey:
#  region:
#  s3:
#    bucketName:

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 9090
management:
  server:
    port: 8080



