spring:
  datasource:
    username:
    password:
    url:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    header:
    secret:
    token-validity-in-seconds:

aws:
  accessKeyId:
  secretKey:
  region:
  s3:
    bucketName:

logging:
  level:
    org.springframework.security: DEBUG





