spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    tomcat:
      validation-query: "select 1"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  secret-key: ${SECRET-KEY}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile, email

security:

  accessKeyId: ${ACCESSKEY_ID}
  secretKey: ${SECRET_KEY}
  region: ${REGION}
  s3:
    bucketName: ${BUCKET_NAME}

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 9090
management:
  server:
    port: 8080



