spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    tomcat:
      validation-query: "select 1"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            scope: profile, email
  secret-key: ${SECRET-KEY}
#security:
#  jwt:
#    header:
#    secret:
#    token-validity-in-seconds:
#
#aws:
#  accessKeyId:
#  secretKey:
#  region:
#  s3:
#    bucketName:

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 9090
management:
  server:
    port: 8080



