spring:
  datasource:
    username: backend2team
    password: supercoding09
    url: jdbc:mariadb://db-project3.cryqvukdhzno.ap-northeast-2.rds.amazonaws.com:3306/communityRoom
    tomcat:
      validation-query: "select 1"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email

    secret-key: supercoding

aws:
  accessKeyId: AKIA2WSJ73WOI2ZIWIMW
  secretKey: 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
  region: ap-northeast-2
  s3:
    bucketName: project2team

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 9090
management:
  server:
    port: 8080


